CREATE DATABASE IF NOT EXISTS Burguer;
USE Burguer;

CREATE TABLE IF NOT EXISTS Produtos(
CODIGO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
PRODUTO VARCHAR(50),
DESCRICAO VARCHAR(200),
PRECO FLOAT,
DESTAQUE
FOTO VARCHAR(270),
DISPONIBILIDADE VARCHAR(100)
)