CREATE DATABASE IF NOT EXISTS Produtos;
USE Produtos;

CREATE TABLE IF NOT EXISTS Produtos (
    CODIGO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PRODUTO VARCHAR(50),
    DESCRICAO VARCHAR(200),
    DESTAQUE BOOL,
    PRECO FLOAT,
    FOTO VARCHAR(270),
    DISPONIBILIDADE BOOL
);

CREATE TABLE IF NOT EXISTS Usuarios (
    USUARIO VARCHAR(20) PRIMARY KEY,
    SENHA VARCHAR(200) NOT NULL,
    NOME VARCHAR(100) DEFAULT 'ANONIMO'
);

CREATE TABLE IF NOT EXISTS Carrinhos (
    COD_CARRINHO INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO VARCHAR(20),
    DATA DATETIME DEFAULT CURRENT_TIMESTAMP,
    FINALIZADO BOOL,
    
    CONSTRAINT FK_CARRINHO_USUARIO 
    FOREIGN KEY (USUARIO) 
    REFERENCES Usuarios(USUARIO)
);

CREATE TABLE IF NOT EXISTS Itens_Carrinhos (
    COD_ITENS_CARRINHOS INT AUTO_INCREMENT PRIMARY KEY,
    COD_CARRINHO INT,
    COD_PRODUTO INT,
    QUANTIDADE INT DEFAULT 1,

    CONSTRAINT FK_ITENSCARRINHO_CARRINHOS 
    FOREIGN KEY (COD_CARRINHO) 
    REFERENCES Carrinhos(COD_CARRINHO),

    CONSTRAINT FK_ITENSCARRINHO_PRODUTO 
    FOREIGN KEY (COD_PRODUTO) 
    REFERENCES Produtos(CODIGO)
);


SELECT 
    Carrinhos.COD_CARRINHO,
    Usuarios.USUARIO,
    Carrinhos.DATA,
    Carrinhos.FINALIZADO,
    Produtos.PRODUTO,
    Itens_Carrinhos.QUANTIDADE,
    Produtos.PRECO,
    Produtos.FOTO
FROM Carrinhos

INNER JOIN Usuarios 
    ON Usuarios.USUARIO = Carrinhos.USUARIO

INNER JOIN Itens_Carrinhos 
    ON Carrinhos.COD_CARRINHO = Itens_Carrinhos.COD_CARRINHO

INNER JOIN Produtos 
    ON Produtos.CODIGO = Itens_Carrinhos.COD_PRODUTO

WHERE Usuarios.USUARIO = 'godothalya';

-- INSERTS USUÁRIOS
INSERT INTO Usuarios (USUARIO, SENHA, NOME)
VALUES ('nathalya', '123', 'nathy');

INSERT INTO Usuarios (USUARIO, SENHA, NOME)
VALUES ('godofredo', '1234', 'godosantos');

INSERT INTO Usuarios (USUARIO, SENHA, NOME)
VALUES ('godothalya', '6969', 'godofredo');


INSERT INTO Produtos (PRODUTO, DESCRICAO, PRECO, FOTO)
VALUES (
    'hamburguer 2',
    'gostoso',
    37.90,
    'https://cloudfront-us-east-1.images.arcpublishing.com/estadao/77XTHHCCLBEXLC2Y5RK4PN37CE.jpg'
);

INSERT INTO Produtos (PRODUTO, DESCRICAO, PRECO, FOTO)
VALUES (
    'hamburguer 3',
    'muito bom',
    56.90,
    'https://www.seara.com.br/wp-content/uploads/2025/09/shutterstock_1489640750-1.jpg'
);